env:
  TERM: xterm-256color
window:
  dimensions:
    columns: 0
    lines: 0
  padding:
    x: 24
    y: 16
  dynamic_padding: false
  decorations: buttonless

scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 10000

  # Number of lines the viewport will move for every line scrolled when
  # scrollback is enabled (history > 0).
  multiplier: 3

  # Scroll to the bottom when new text is written to the terminal.
  auto_scroll: false

font:
  # Normal (roman) font face
  normal:
    # Font family
    #
    # Default:
    #   - (macOS) Menlo
    #   - (Linux/BSD) monospace
    #   - (Windows) Consolas
    family: DM Mono 

    # The `style` can be specified to pick a specific face.
    style: Regular

  # Bold font face
  bold:
    # Font family
    #
    # If the bold family is not specified, it will fall back to the
    # value specified for the normal font.
    family: DM Mono

    # The `style` can be specified to pick a specific face.
    style: Medium

  # Italic font face
  italic:
    # Font family
    #
    # If the italic family is not specified, it will fall back to the
    # value specified for the normal font.
    family: DM Mono

    # The `style` can be specified to pick a specific face.
    style: Italic

  # Bold italic font face
  bold_italic:
    # Font family
    #
    # If the bold italic family is not specified, it will fall back to the
    # value specified for the normal font.
    family: DM Mono

    # The `style` can be specified to pick a specific face.
    style: Medium Italic

  size: 16.0

cursor:
  # Cursor style
  style:
    # Cursor shape
    #
    # Values for `shape`:
    #   - ▇ Block
    #   - _ Underline
    #   - | Beam
    shape: Block

# Colors
colors:
  # Tomorrow (https://github.com/aarowill/base16-alacritty/blob/master/colors/base16-tomorrow.yml)
  primary:
    background: '0x1d1f21'
    foreground: '0xc5c8c6'
  # # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x1d1f21'
    cursor: '0xc5c8c6'
  # # Normal colors
  normal:
    black:   '0x1d1f21'
    red:     '0xcc6666'
    green:   '0xb5bd68'
    yellow:  '0xf0c674'
    blue:    '0x81a2be'
    magenta: '0xb294bb'
    cyan:    '0x8abeb7'
    white:   '0xc5c8c6'
  # # Bright colors
  bright:
    black:   '0x969896'
    red:     '0xde935f'
    green:   '0x282a2e'
    yellow:  '0x373b41'
    blue:    '0xb4b7b4'
    magenta: '0xe0e0e0'
    cyan:    '0xa3685a'
    white:   '0xffffff'

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"


key_bindings:
  # - { key: N,        mods: Command, command: { program: "open", args: ["-n", "/Applications/Alacritty.app"] } }
  - { key: N,        mods: Command, action: SpawnNewInstance            }
  - { key: V,        mods: Command, action: Paste                        }
  - { key: C,        mods: Command, action: Copy                         }
  - { key: Paste,                   action: Paste                        }
  - { key: Copy,                    action: Copy                         }
